"""add outreach drafts

Revision ID: 235e75395d7f
Revises: 361096957136
Create Date: 2026-08-27 20:33:09.921849

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "235e75395d7f"
down_revision: str | Sequence[str] | None = "361096957136"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outreach_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Enum("INVITE", "DECLINE", name="outreach_kind"), nullable=False),
        sa.Column(
            "state", sa.Enum("DRAFT", "SENT", "FAILED", name="outreach_state"), nullable=False
        ),
        sa.Column("subject", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("template_version", sa.String(length=40), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_outreach_drafts_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outreach_drafts")),
        sa.UniqueConstraint("application_id", name=op.f("uq_outreach_drafts_application_id")),
    )
    op.create_index(op.f("ix_outreach_drafts_state"), "outreach_drafts", ["state"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_drafts_state"), table_name="outreach_drafts")
    op.drop_table("outreach_drafts")

    # SQLAlchemy creates native enum types implicitly when the tables that use
    # them are created, but autogenerate never emits the matching DROP TYPE.
    # Without this, `downgrade base` leaves the types behind and the next
    # `upgrade head` fails with "type already exists".
    for enum_name in ("outreach_kind", "outreach_state"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
