"""add share links

Revision ID: 27f1acd17546
Revises: 235e75395d7f
Create Date: 2026-08-28 08:47:23.135235

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27f1acd17546"
down_revision: str | Sequence[str] | None = "235e75395d7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "share_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_opening_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.Enum("SHORTLIST", "OPENING", name="share_scope"), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("last_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_opening_id"],
            ["job_openings.id"],
            name=op.f("fk_share_links_job_opening_id_job_openings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_share_links_token_hash")),
    )
    op.create_index(
        op.f("ix_share_links_job_opening_id"), "share_links", ["job_opening_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_share_links_job_opening_id"), table_name="share_links")
    op.drop_table("share_links")

    # autogenerate never emits DROP TYPE for a native enum it created
    # implicitly. Without this, `downgrade base` leaves the type behind and the
    # next `upgrade head` fails. tests/test_migrations.py enforces it.
    op.execute("DROP TYPE IF EXISTS share_scope")
    # ### end Alembic commands ###
