"""add indexes, review flags and runtime state

Revision ID: 6f5d5dce4c0d
Revises: f144bdd742a2
Create Date: 2026-08-27 18:25:42.492244

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5d5dce4c0d"
down_revision: str | Sequence[str] | None = "f144bdd742a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runtime_state",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runtime_state")),
        sa.UniqueConstraint("key", name=op.f("uq_runtime_state_key")),
    )
    op.create_index(
        op.f("ix_applications_candidate_id"), "applications", ["candidate_id"], unique=False
    )
    op.create_index(
        op.f("ix_criterion_scores_criterion_id"), "criterion_scores", ["criterion_id"], unique=False
    )
    # Existing rows need a value before the column can be NOT NULL.
    op.add_column(
        "evaluations",
        sa.Column(
            "review_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column("evaluations", "review_flags", server_default=None)
    op.create_index(
        op.f("ix_job_openings_company_id"), "job_openings", ["company_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_queue_application_id"), "job_queue", ["application_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_queue_application_id"), table_name="job_queue")
    op.drop_index(op.f("ix_job_openings_company_id"), table_name="job_openings")
    op.drop_column("evaluations", "review_flags")
    op.drop_index(op.f("ix_criterion_scores_criterion_id"), table_name="criterion_scores")
    op.drop_index(op.f("ix_applications_candidate_id"), table_name="applications")
    op.drop_table("runtime_state")
    # ### end Alembic commands ###
